const GenerateFrontendFiles = (specification) => {
  if (!specification) {
    throw new Error("Generation specification is required");
  }

  const pages = Array.isArray(specification.pages)
    ? specification.pages
    : [];

  const pageFiles = pages.map((page) => {
    const componentName = NormalizeComponentName(page);

    return {
      type: "page",
      page,
      filename: `${componentName}.jsx`,
      componentName,
      content: GeneratePageComponent(
        componentName,
        page
      ),
    };
  });

  return {
    pageFiles,
  };
};

const NormalizeComponentName = (pageName) => {
  return pageName
    .replace(/[^a-zA-Z0-9 ]/g, "")
    .split(" ")
    .filter(Boolean)
    .map(
      (word) =>
        word.charAt(0).toUpperCase() +
        word.slice(1)
    )
    .join("");
};

const GeneratePageComponent = (
  componentName,
  displayName
) => {
  return `import React from "react";

const ${componentName} = () => {
  return (
    <div>
      <h1>${displayName}</h1>

      <p>
        This page was generated by CoreCraft.
      </p>
    </div>
  );
};

export default ${componentName};
`;
};

module.exports = {
  GenerateFrontendFiles,
  NormalizeComponentName,
  GeneratePageComponent,
};