const GenerateServerPackageJson = (appName) => {
  return JSON.stringify(
    {
      name: `${appName.toLowerCase()}-server`,
      version: "1.0.0",
      main: "Src/Server.js",
      scripts: {
        start: "node Src/Server.js",
        dev: "nodemon Src/Server.js",
      },
      dependencies: {
        bcrypt: "^5.1.1",
        cors: "^2.8.5",
        dotenv: "^16.4.5",
        express: "^4.21.0",
        jsonwebtoken: "^9.0.2",
        mongoose: "^8.7.0",
      },
      devDependencies: {
        nodemon: "^3.1.7",
      },
    },
    null,
    2
  );
};

const GenerateClientPackageJson = (appName) => {
  return JSON.stringify(
    {
      name: `${appName.toLowerCase()}-client`,
      private: true,
      version: "0.0.0",
      type: "module",
      scripts: {
        dev: "vite",
        build: "vite build",
        preview: "vite preview",
      },
      dependencies: {
        "@vitejs/plugin-react": "^4.3.3",
        axios: "^1.7.7",
        react: "^18.3.1",
        "react-dom": "^18.3.1",
        "react-router-dom": "^6.27.0",
        vite: "^5.4.10",
      },
      devDependencies: {},
    },
    null,
    2
  );
};

const GenerateServerFile = () => {
  return `require("dotenv").config();

const app = require("./App");

const PORT = process.env.PORT || 5000;

app.listen(PORT, () => {
  console.log(\`Server running on port \${PORT}\`);
});
`;
};

const GenerateServerAppFile = (
  entities = [],
  features = []
) => {
  const routeImports = entities
    .map(
      (entity) =>
        `const ${entity}Routes = require("./Routes/${entity}Routes");`
    )
    .join("\n");

  const routeRegistrations = entities
    .map(
      (entity) =>
        `app.use("/api/${entity.toLowerCase()}", ${entity}Routes);`
    )
    .join("\n");

  const normalizedFeatures = features.map(
    (feature) => feature.toLowerCase()
  );

  const hasAuthentication =
    normalizedFeatures.some(
      (feature) =>
        feature.includes("login") ||
        feature.includes("auth") ||
        feature.includes("register")
    );

  const authImport = hasAuthentication
    ? `const AuthRoutes = require("./Routes/AuthRoutes");`
    : "";

  const authRegistration = hasAuthentication
    ? `app.use("/api/auth", AuthRoutes);`
    : "";

  return `const express = require("express");
const cors = require("cors");
const mongoose = require("mongoose");

${routeImports}
${authImport}

const app = express();

app.use(cors());
app.use(express.json());

mongoose
  .connect(process.env.MONGO_URI)
  .then(() => {
    console.log("MongoDB connected");
  })
  .catch((error) => {
    console.error(
      "MongoDB connection error:",
      error.message
    );
  });

${authRegistration}

${routeRegistrations}

app.get("/", (req, res) => {
  res.json({
    message: "Generated by CoreCraft",
  });
});

module.exports = app;
`;
};

const GenerateEnvironmentFile = (appName) => {
  return `PORT=5001
MONGO_URI=mongodb://127.0.0.1:27017/${appName}DB
JWT_SECRET=change_this_secret
`;
};

const GenerateClientEnvironmentFile = () => {
  return `VITE_API_URL=http://localhost:5001/api
`;
};

const GenerateMainJsx = () => {
  return `import React from "react";
import ReactDOM from "react-dom/client";
import { BrowserRouter } from "react-router-dom";

import App from "./App";
import { AuthProvider } from "./Context/AuthContext";

import "./Styles/theme.css";

ReactDOM.createRoot(
  document.getElementById("root")
).render(
  <React.StrictMode>
    <BrowserRouter>
      <AuthProvider>
        <App />
      </AuthProvider>
    </BrowserRouter>
  </React.StrictMode>
);
`;
};

const GenerateAppJsx = (
  pages = [],
  features = []
) => {
  const normalizedPages =
    pages.map((page) => ({
      page,
      componentName:
        NormalizeComponentName(page),
      route:
        CreateRoutePath(page),
    }));

  const pageImports =
    normalizedPages
      .map(
        ({ componentName }) =>
          `import ${componentName} from "./Pages/${componentName}";`
      )
      .join("\n");

  const hasAuthentication =
    features.some((feature) => {
      const normalized =
        feature.toLowerCase();

      return (
        normalized.includes("login") ||
        normalized.includes("auth") ||
        normalized.includes("register")
      );
    });

  const protectedRouteImport =
    hasAuthentication
      ? `import ProtectedRoute from "./Routes/ProtectedRoute";`
      : "";

  const navbarImport =
    hasAuthentication
      ? `import Navbar from "./Components/Navbar";`
      : "";

  const hasRegisterPage =
    normalizedPages.some(
      ({ componentName }) =>
        componentName === "RegisterPage"
    );

  const extraRegisterImport =
    hasAuthentication &&
    !hasRegisterPage
      ? `import RegisterPage from "./Pages/RegisterPage";`
      : "";

  const routeDefinitions =
    normalizedPages
      .map(
        ({
          page,
          componentName,
          route,
        }) => {
          const pageName =
            page.toLowerCase();

          const path =
            pageName === "home page"
              ? "/"
              : `/${route}`;

          const isLogin =
            componentName ===
            "LoginPage";

          const isRegister =
            componentName ===
            "RegisterPage";

          const isInstructorPortal =
            componentName ===
            "InstructorPortal";

          if (
            !hasAuthentication ||
            isLogin ||
            isRegister
          ) {
            return `        <Route path="${path}" element={<${componentName} />} />`;
          }

          if (
            pageName === "home page"
          ) {
            return `        <Route
          path="${path}"
          element={
            <>
              <Navbar />
              <${componentName} />
            </>
          }
        />`;
          }

          if (
            isInstructorPortal
          ) {
            return `        <Route
          path="${path}"
          element={
            <ProtectedRoute roles={["instructor", "admin"]}>
              <>
                <Navbar />
                <${componentName} />
              </>
            </ProtectedRoute>
          }
        />`;
          }

          return `        <Route
          path="${path}"
          element={
            <ProtectedRoute>
              <>
                <Navbar />
                <${componentName} />
              </>
            </ProtectedRoute>
          }
        />`;
        }
      )
      .join("\n");

  const registerRoute =
    hasAuthentication &&
    !hasRegisterPage
      ? `        <Route path="/register" element={<RegisterPage />} />`
      : "";

  return `import React from "react";

import {
  Routes,
  Route,
} from "react-router-dom";

${pageImports}

${protectedRouteImport}
${navbarImport}
${extraRegisterImport}

const App = () => {
  return (
    <Routes>
${routeDefinitions}

${registerRoute}
    </Routes>
  );
};

export default App;
`;
};

const GenerateIndexHtml = (appName) => {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0"
    />

    <title>${appName}</title>
  </head>

  <body>
    <div id="root"></div>

    <script
      type="module"
      src="/src/main.jsx"
    ></script>
  </body>
</html>
`;
};

const NormalizeComponentName = (pageName) => {
  return pageName
    .replace(/[^a-zA-Z0-9 ]/g, "")
    .split(" ")
    .filter(Boolean)
    .map(
      (word) =>
        word.charAt(0).toUpperCase() +
        word.slice(1)
    )
    .join("");
};

const CreateRoutePath = (pageName) => {
  return pageName
    .toLowerCase()
    .replace(/\s+page$/i, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
};

module.exports = {
  GenerateServerPackageJson,
  GenerateClientPackageJson,
  GenerateServerFile,
  GenerateServerAppFile,
  GenerateEnvironmentFile,
  GenerateClientEnvironmentFile,
  GenerateMainJsx,
  GenerateAppJsx,
  GenerateIndexHtml,
};