const GenerateServerPackageJson = (appName) => {
  return JSON.stringify(
    {
      name: `${appName.toLowerCase()}-server`,
      version: "1.0.0",
      main: "Src/Server.js",
      scripts: {
        start: "node Src/Server.js",
        dev: "nodemon Src/Server.js",
      },
      dependencies: {
        bcrypt: "^5.1.1",
        cors: "^2.8.5",
        dotenv: "^16.4.5",
        express: "^4.21.0",
        jsonwebtoken: "^9.0.2",
        mongoose: "^8.7.0",
      },
      devDependencies: {
        nodemon: "^3.1.7",
      },
    },
    null,
    2
  );
};

const GenerateClientPackageJson = (appName) => {
  return JSON.stringify(
    {
      name: `${appName.toLowerCase()}-client`,
      private: true,
      version: "0.0.0",
      type: "module",
      scripts: {
        dev: "vite",
        build: "vite build",
        preview: "vite preview",
      },
      dependencies: {
        "@vitejs/plugin-react": "^4.3.3",
        axios: "^1.7.7",
        react: "^18.3.1",
        "react-dom": "^18.3.1",
        "react-router-dom": "^6.27.0",
        vite: "^5.4.10",
      },
      devDependencies: {},
    },
    null,
    2
  );
};

const GenerateServerFile = () => {
  return `require("dotenv").config();

const app = require("./App");

const PORT = process.env.PORT || 5000;

app.listen(PORT, () => {
  console.log(\`Server running on port \${PORT}\`);
});
`;
};

const GenerateServerAppFile = (
  specification = {}
) => {
  const entities =
    Array.isArray(
      specification.entities
    )
      ? specification.entities
      : [];

  const apiModules =
    Array.isArray(
      specification.apiModules
    )
      ? specification.apiModules
      : [];

  const roles =
    Array.isArray(
      specification.roles
    )
      ? specification.roles
      : [];

  const pages =
    Array.isArray(
      specification.pages
    )
      ? specification.pages
      : [];

  const hasAuthentication =
    roles.length > 0 ||
    pages.some(
      (page) =>
        page?.protected === true
    ) ||
    apiModules.some(
      (module) =>
        module?.protected === true
    );

  const hasLookups =
    entities.some(
      (entity) =>
        (entity.fields || [])
          .some(
            (field) =>
              field.type ===
                "ObjectId" &&
              field.ref
          )
    );

  /* -----------------------------------------
     Generate route imports dynamically
     ----------------------------------------- */

  const routeImports =
    entities
      .map((entity) => {
        const entityName =
          GetEntityName(entity);

        if (!entityName) {
          return "";
        }

        return `const ${entityName}Routes =
  require("./Routes/${entityName}Routes");`;
      })
      .filter(Boolean)
      .join("\n");


  /* -----------------------------------------
     Generate route registrations dynamically
     ----------------------------------------- */

  const routeRegistrations =
    entities
      .map((entity) => {
        const entityName =
          GetEntityName(entity);

        if (!entityName) {
          return "";
        }

        const routeName =
          entityName.toLowerCase();

        return `app.use(
  "/api/${routeName}",
  ${entityName}Routes
);`;
      })
      .filter(Boolean)
      .join("\n");


  /* -----------------------------------------
     Authentication route
     ----------------------------------------- */

  const authImport =
    hasAuthentication
      ? `const AuthRoutes =
  require("./Routes/AuthRoutes");`
      : "";

  const authRegistration =
    hasAuthentication
      ? `app.use(
  "/api/auth",
  AuthRoutes
);`
      : "";

  const lookupImport =
    hasLookups
      ? `const LookupRoutes =
  require("./Routes/LookupRoutes");`
      : "";

  const lookupRegistration =
    hasLookups
      ? `app.use(
  "/api/lookups",
  LookupRoutes
);`
      : "";


  return `const express =
  require("express");

const cors =
  require("cors");

const mongoose =
  require("mongoose");

${routeImports}

${authImport}

${lookupImport}


const app =
  express();


app.use(cors());

app.use(
  express.json()
);


mongoose
  .connect(
    process.env.MONGO_URI
  )
  .then(() => {
    console.log(
      "MongoDB connected"
    );
  })
  .catch((error) => {
    console.error(
      "MongoDB connection error:",
      error.message
    );
  });


${authRegistration}

${lookupRegistration}

${routeRegistrations}


app.get(
  "/",
  (req, res) => {
    res.json({
      message:
        "Generated by CoreCraft",
    });
  }
);


module.exports =
  app;
`;
};

const GenerateEnvironmentFile = (
  appName = "Application"
) => {
  const databaseName =
    appName
      .replace(
        /[^a-zA-Z0-9]/g,
        ""
      ) ||
    "Application";

  return `PORT=5001
MONGO_URI=mongodb://127.0.0.1:27017/${databaseName}DB
JWT_SECRET=change_this_secret
`;
};

const GenerateClientEnvironmentFile = () => {
  return `VITE_API_URL=http://localhost:5001/api
`;
};

const GenerateMainJsx = (
  specification = {}
) => {
  const roles =
    Array.isArray(
      specification.roles
    )
      ? specification.roles
      : [];

  const pages =
    Array.isArray(
      specification.pages
    )
      ? specification.pages
      : [];

  const apiModules =
    Array.isArray(
      specification.apiModules
    )
      ? specification.apiModules
      : [];

  const hasAuthentication =
    roles.length > 0 ||
    pages.some(
      (page) =>
        page?.protected === true
    ) ||
    apiModules.some(
      (module) =>
        module?.protected === true
    );


  const authImport =
    hasAuthentication
      ? `import {
  AuthProvider,
} from "./Context/AuthContext";`
      : "";


  const appContent =
    hasAuthentication
      ? `<AuthProvider>
        <App />
      </AuthProvider>`
      : `<App />`;


  return `import React from "react";


import ReactDOM from "react-dom/client";


import {
  BrowserRouter,
} from "react-router-dom";


import App from "./App";


${authImport}


import "./Styles/theme.css";




ReactDOM.createRoot(
  document.getElementById(
    "root"
  )
).render(
  <React.StrictMode>


    <BrowserRouter>


      ${appContent}


    </BrowserRouter>


  </React.StrictMode>
);
`;
};

const GenerateAppJsx = (
  specification = {}
) => {
  const pages =
    Array.isArray(
      specification.pages
    )
      ? specification.pages
      : [];

  const roles =
    Array.isArray(
      specification.roles
    )
      ? specification.roles
      : [];

  const apiModules =
    Array.isArray(
      specification.apiModules
    )
      ? specification.apiModules
      : [];

  const hasAuthentication =
    roles.length > 0 ||
    pages.some(
      (page) =>
        page?.protected === true
    ) ||
    apiModules.some(
      (module) =>
        module?.protected === true
    );

  const firstPublicPage =
    pages.find(
      (page) =>
        page?.protected !== true &&
        page?.route
    );

  const rootDestination =
    hasAuthentication
      ? "/login"
      : firstPublicPage?.route || null;

  const normalizedRootDestination =
    rootDestination &&
    rootDestination.startsWith("/")
      ? rootDestination
      : rootDestination
        ? `/${rootDestination}`
        : null;

  const rootRoute =
    normalizedRootDestination &&
    normalizedRootDestination !== "/"
      ? `
        <Route
          path="/"
          element={
            <Navigate
              to="${normalizedRootDestination}"
              replace
            />
          }
        />
`
      : "";


  /* -----------------------------------------
     Normalize generated pages
     ----------------------------------------- */

  const normalizedPages =
    pages.map((page) => {
      const pageName =
        GetPageName(page);

      return {
        page,
        pageName,

        componentName:
          NormalizeComponentName(
            pageName
          ),

        route:
          GetPageRoute(page),

        protected:
          page?.protected === true,

        roles:
          Array.isArray(
            page?.roles
          )
            ? page.roles
            : [],
      };
    });


  /* -----------------------------------------
     Page imports
     ----------------------------------------- */

  const pageImports =
    normalizedPages
      .map(
        ({
          componentName,
        }) =>
          `import ${componentName}
  from "./Pages/${componentName}";`
      )
      .join("\n");


  const authImports =
    hasAuthentication
      ? `
import ProtectedRoute
  from "./Routes/ProtectedRoute";

import Navbar
  from "./Components/Navbar";

import LoginPage
  from "./Pages/LoginPage";

import RegisterPage
  from "./Pages/RegisterPage";
`
      : "";


  /* -----------------------------------------
     Dynamic page routes
     ----------------------------------------- */

  const routeDefinitions =
    normalizedPages
      .map(
        ({
          componentName,
          route,
          protected:
            isProtected,
          roles:
            pageRoles,
        }) => {
          const path =
            route.startsWith("/")
              ? route
              : `/${route}`;

          /*
            Public application
          */
          if (
            !hasAuthentication
          ) {
            return `
        <Route
          path="${path}"
          element={
            <${componentName} />
          }
        />`;
          }


          /*
            Public page inside an
            authenticated application
          */
          if (
            !isProtected
          ) {
            return `
        <Route
          path="${path}"
          element={
            <>
              <Navbar />

              <${componentName} />
            </>
          }
        />`;
          }


          /*
            Protected page with
            optional role restrictions
          */
          const rolesProperty =
            pageRoles.length > 0
              ? ` roles={${JSON.stringify(
                  pageRoles
                )}}`
              : "";

          return `
        <Route
          path="${path}"
          element={
            <ProtectedRoute${rolesProperty}>

              <>

                <Navbar />

                <${componentName} />

              </>

            </ProtectedRoute>
          }
        />`;
        }
      )
      .join("\n");


  /* -----------------------------------------
     Authentication routes
     ----------------------------------------- */

  const authenticationRoutes =
    hasAuthentication
      ? `
        <Route
          path="/login"
          element={
            <LoginPage />
          }
        />

        <Route
          path="/register"
          element={
            <RegisterPage />
          }
        />
`
      : "";


  return `import React from "react";

import {
  Routes,
  Route,
  Navigate,
} from "react-router-dom";


${pageImports}

${authImports}


const App = () => {
  return (
    <Routes>

${rootRoute}

${authenticationRoutes}

${routeDefinitions}

        <Route
          path="*"
          element={
            <Navigate
              to="/"
              replace
            />
          }
        />

    </Routes>
  );
};


export default App;
`;
};

const GetEntityName = (entity) => {
  if (typeof entity === "string") {
    return NormalizeEntityName(entity);
  }

  return NormalizeEntityName(
    entity?.name || ""
  );
};

const NormalizeEntityName = (name = "") => {
  return name
    .trim()
    .replace(/[^a-zA-Z0-9]+(.)/g, (_, char) =>
      char.toUpperCase()
    )
    .replace(/^./, (char) =>
      char.toUpperCase()
    );
};

const GetPageName = (page) => {
  if (typeof page === "string") {
    return page;
  }

  return page?.name || "";
};

const GetPageRoute = (page) => {
  if (
    typeof page === "object" &&
    page?.route
  ) {
    return page.route.replace(/^\//, "");
  }

  return CreateRoutePath(
    GetPageName(page)
  );
};

const GenerateIndexHtml = (appName) => {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0"
    />

    <title>${appName}</title>
  </head>

  <body>
    <div id="root"></div>

    <script
      type="module"
      src="/src/main.jsx"
    ></script>
  </body>
</html>
`;
};

const NormalizeComponentName = (pageName) => {
  return pageName
    .replace(/[^a-zA-Z0-9 ]/g, "")
    .split(" ")
    .filter(Boolean)
    .map(
      (word) =>
        word.charAt(0).toUpperCase() +
        word.slice(1)
    )
    .join("");
};

const CreateRoutePath = (pageName) => {
  return pageName
    .toLowerCase()
    .replace(/\s+page$/i, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
};

module.exports = {
  GenerateServerPackageJson,
  GenerateClientPackageJson,
  GenerateServerFile,
  GenerateServerAppFile,
  GenerateEnvironmentFile,
  GenerateClientEnvironmentFile,
  GenerateMainJsx,
  GenerateAppJsx,
  GenerateIndexHtml,
};
