const express =
  require("express");

const cors =
  require("cors");

const mongoose =
  require("mongoose");

const ProjectRoutes =
  require("./Routes/ProjectRoutes");
const TaskRoutes =
  require("./Routes/TaskRoutes");

const AuthRoutes =
  require("./Routes/AuthRoutes");

const LookupRoutes =
  require("./Routes/LookupRoutes");


const app =
  express();


// Shared middleware used by every API route in this generated backend.
app.use(cors());

app.use(
  express.json()
);


// Connects the generated Express server to the MongoDB database.
mongoose
  .connect(
    process.env.MONGO_URI
  )
  .then(() => {
    console.log(
      "MongoDB connected"
    );
  })
  .catch((error) => {
    console.error(
      "MongoDB connection error:",
      error.message
    );
  });


// Authentication and lookup routes support the generated role-based pages.
app.use(
  "/api/auth",
  AuthRoutes
);

app.use(
  "/api/lookups",
  LookupRoutes
);

// Business API routes generated from the CoreCraft application blueprint.
// The blueprint was shaped with AI assistance, then written as standard Express code.
app.use(
  "/api/project",
  ProjectRoutes
);
app.use(
  "/api/task",
  TaskRoutes
);


app.get(
  "/",
  (req, res) => {
    res.json({
      message:
        "Generated by CoreCraft",
    });
  }
);


module.exports =
  app;
